all:
  children:
    rack01:
      hosts:
        node001.lab.local:
          ansible_host: 10.10.1.11
        node002.lab.local:
          ansible_host: 10.10.1.12
    gpu_nodes:
      hosts:
        node001.lab.local:
